/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package evolu

class App {
    val greeting: String
        get() {
            return "Hello world."
        }
}

/*
* - Field
* - Robot
*     - Position
*     - Genome
*     - Statistics
* - Cpu
*
* */


fun main() {
    println("Evolution starts now...")

    val field = Field(7,7)

    field.randomize()
    field.visualize()
}
