/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package evolu

class App {
    val greeting: String
        get() {
            return "Hello world."
        }
}

/*
* + Field
* - Robot
*     - Position, direction
*     - Genome
*       - String[54]
*     - Statistics
*       - collected diamonds
*       - used steps
* - Cpu
*
* */

fun main() {
    println("Evolution starts now...")

    val field = Field(7,7)

    field.randomize()
    field.visualize(Point(4, 4))
}
